bagtube_server:
  ros__parameters:
    max_total_size_gb: 0.0  # no limit
    toggle_input_nodes_running_services: [set_capture, image_raw/enable_encoder]
    pipes: [image_raw]
    image_raw:
      type: h264_msgs/msg/Packet
      input_topic: /image_raw/h264
      output_topic: /image_stream/h264
