#codecName_ = get_safe_param<std::string>(node, ns + "encoding", "libx264");
#profile_ = get_safe_param<std::string>(node, ns + "profile", "");
#preset_ = get_safe_param<std::string>(node, ns + "preset", "");
#tune_ = get_safe_param<std::string>(node, ns + "tune", "");
#delay_ = get_safe_param<std::string>(node, ns + "delay", "");
#qmax_ = get_safe_param<int>(node, ns + "qmax", 10);
#bitRate_ = get_safe_param<int64_t>(node, ns + "bit_rate", 8242880);
#GOPSize_ = get_safe_param<int64_t>(node, ns + "gop_size", 15);
#pixFormat_ = pixelFormat(get_safe_param<std::string>(node, ns + "pixel_format", ""));

camera_node:
  ros__parameters:
    format: NV21
    role: video
    width: 640
    height: 480
    ffmpeg_image_transport:
      encoding: "libx264"
      profile: "main"
      preset: "ultrafast"
      tune: "zerolatency"
      delay: "1"
      qmax: 63
      bit_rate: 8242880
      crf: "21"
      gop_size: 15
      pixel_format: "rgb8"

h264_decoder:
  ros__parameters:
    ffmpeg_image_transport:
      map.h264: "h264"
